### ISSUE TITLE
Original error stack trace: Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by juqkai** [NJAldwin/eleventy-plugin-gen-favicons#15]
```
[11ty] Writing dist/searchIndex.json from ./src/site/search-index.njk
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "dist/index.html" from "./src/site/notes/test.md" (via EleventyTemplateError)
[11ty] 2. (./src/site/_includes/layouts/note.njk)
[11ty]   Template render error: (E:\digitalgarden\src\site\_includes\components\pageheader.njk)
[11ty]   EleventyShortcodeError: Error with Nunjucks shortcode `favicons` (via Template render error)
[11ty] 3. EBUSY: resource busy or locked, copyfile 'E:\digitalgarden\src\site\favicon.svg' -> 'E:\digitalgarden\dist\favicon.svg' (via Template render error)
[11ty]
[11ty] Original error stack trace: Error: EBUSY: resource busy or locked, copyfile 'E:\digitalgarden\src\site\favicon.svg' -> 'E:\digitalgarden\dist\favicon.svg'
[11ty]     at async Object.copyFile (node:internal/fs/promises:621:10)
[11ty]     at async module.exports (E:\digitalgarden\node_modules\eleventy-plugin-gen-favicons\favicon-gen.js:88:7)
[11ty]     at async Object.<anonymous> (E:\digitalgarden\node_modules\eleventy-plugin-gen-favicons\index.js:25:28)
[11ty] Copied 7 files / Wrote 0 files in 0.40 seconds (v2.0.1)
```

**Comment by cgbeutler** [comment]
Saw with Eleventy 3.1.2 in a big project. The collision is random and changes files each time.
